let state={stars:0,seen:[],best:0,correct:0,sessions:0,muted:false};try{state={...state,...JSON.parse(localStorage.getItem('viraState')||'{}')}}catch(e){localStorage.removeItem('viraState')}
let stars=+state.stars||0,seen=new Set(state.seen||[]),best=+state.best||0,correct=+state.correct||0,sessions=+state.sessions||0,muted=!!state.muted,current='',queue=[],roundTimer=null,left=60,audio=null,music=null;
const $=id=>document.getElementById(id),save=()=>localStorage.setItem('viraState',JSON.stringify({stars,seen:[...seen],best,correct,sessions,muted}));
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));const target=$(id);if(target)target.classList.add('on');scrollTo(0,0)}
function sync(){document.querySelectorAll('[data-stars]').forEach(x=>x.textContent=stars);document.querySelectorAll('[data-mute]').forEach(x=>x.textContent=muted?'🔇':'🔊');save()}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function pool(){return current==='Tudo'?Object.entries(DATA).flatMap(([c,a])=>a.map(w=>[w,c])):DATA[current].map(w=>[w,current])}
function nextCard(){if(!queue.length)queue=shuffle(pool().slice());return queue.pop()}
function ac(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}
function tone(f,d=.08,type='sine',v=.025,t=0){if(muted)return;const a=ac(),o=a.createOscillator(),g=a.createGain(),at=t||a.currentTime;o.type=type;o.frequency.value=f;o.connect(g);g.connect(a.destination);g.gain.setValueAtTime(Math.max(v,.0001),at);g.gain.exponentialRampToValueAtTime(.001,at+d);o.start(at);o.stop(at+d)}
function noise(d=.05,v=.012,f=7000,t=0){if(muted)return;const a=ac(),at=t||a.currentTime,frames=Math.max(1,Math.floor(a.sampleRate*d)),buf=a.createBuffer(1,frames,a.sampleRate),data=buf.getChannelData(0);for(let i=0;i<frames;i++)data[i]=Math.random()*2-1;const src=a.createBufferSource(),filter=a.createBiquadFilter(),g=a.createGain();filter.type='highpass';filter.frequency.value=f;src.buffer=buf;src.connect(filter);filter.connect(g);g.connect(a.destination);g.gain.setValueAtTime(v,at);g.gain.exponentialRampToValueAtTime(.001,at+d);src.start(at);src.stop(at+d)}
function discoKick(t){if(muted)return;const a=ac(),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.setValueAtTime(135,t);o.frequency.exponentialRampToValueAtTime(48,t+.12);g.gain.setValueAtTime(.065,t);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+.17)}
function discoClap(t){noise(.075,.026,1300,t);noise(.055,.014,2200,t+.018);tone(185,.045,'square',.006,t)}
function musicStart(){if(muted||music)return;const a=ac(),spb=60/120,stepDur=spb/4;let next=a.currentTime+.05,step=0;const bass=[110,110,0,131,147,0,131,110,98,98,0,117,131,0,117,98],chords=[[220,261.63,329.63,392],[196,246.94,293.66,369.99],[174.61,220,261.63,329.63],[196,246.94,293.66,349.23]];music=setInterval(()=>{while(next<a.currentTime+.35){const s=step%16,bar=Math.floor(step/16)%4;if(s%4===0)discoKick(next);if(s===4||s===12)discoClap(next);if(s%2===0)noise(.035,s%4===2?.011:.007,6500,next+.003);if(s===6||s===14)noise(.105,.008,5200,next+.002);if(bass[s]){tone(bass[s],.115,'sawtooth',.011,next);tone(bass[s]*2,.065,'triangle',.004,next)}if(s===2||s===10)chords[bar].forEach((n,i)=>tone(n,.12,'triangle',.0045,next+i*.0015));if(s===15)tone([659.25,587.33,523.25,587.33][bar],.055,'square',.004,next);next+=stepDur;step++}},70)}
function musicStop(){clearInterval(music);music=null}
function sfx(n){if(muted)return;const a=ac(),t=a.currentTime;if(n==='tap'){tone(520,.035,'square',.016,t);tone(720,.045,'triangle',.014,t+.028)}if(n==='flip'){noise(.12,.018,1800,t);tone(240,.08,'sawtooth',.018,t);tone(520,.09,'triangle',.026,t+.055);tone(820,.12,'triangle',.024,t+.11)}if(n==='reveal'){tone(392,.07,'triangle',.026,t);tone(523,.07,'triangle',.03,t+.055);tone(659,.12,'triangle',.034,t+.11)}if(n==='count')tone(640,.06,'square',.028,t);if(n==='tick')tone(880,.04,'square',.02,t);if(n==='tickFast'){tone(1040,.055,'square',.03,t);noise(.025,.008,5000,t)}if(n==='timeout'){tone(330,.11,'sawtooth',.035,t);tone(220,.16,'sawtooth',.035,t+.09);tone(110,.28,'square',.03,t+.22)}if(n==='ok'){tone(660,.08,'triangle',.04,t);tone(790,.08,'triangle',.04,t+.07);tone(990,.15,'triangle',.045,t+.14);noise(.09,.012,4500,t+.12)}if(n==='skip'){tone(420,.07,'triangle',.02,t);tone(310,.1,'triangle',.018,t+.06)}if(n==='bad'){tone(250,.09,'sawtooth',.025,t);tone(180,.12,'sawtooth',.02,t+.07)}}
function renderCategories(){document.querySelectorAll('.cat').forEach(b=>{const a=b.querySelector('.art');if(a&&!a.dataset.ready){a.innerHTML=categoryVisual(b.dataset.cat);a.dataset.ready=1}b.onclick=()=>startCategory(b.dataset.cat)})}
function startCategory(c){current=c;queue=[];sessions++;sync();sfx('tap');musicStart();$('catName').textContent=c;deal();show('game')}
function deal(){$('deck').innerHTML='';for(let i=0;i<4;i++){const b=document.createElement('button');b.className='card';b.innerHTML='<div class="q">?</div><span>VIRA!</span>';b.onclick=()=>{sfx('flip');reveal()};$('deck').appendChild(b)}}
function reveal(){const [word,cat]=nextCard();seen.add(cat+'|'+word);sync();show('reveal');$('answer').style.display='none';$('count').style.display='block';let n=3;$('count').textContent=n;sfx('count');const iv=setInterval(()=>{n--;if(n){$('count').textContent=n;sfx('count')}else{clearInterval(iv);$('count').style.display='none';$('word').textContent=word;$('answerVisual').innerHTML=renderIcons(word,cat);$('answer').style.display='block';sfx('reveal');startTimer()}},560)}
function startTimer(){clearInterval(roundTimer);left=60;$('timeLeft').textContent=left;$('timerBadge').classList.remove('danger');roundTimer=setInterval(()=>{left--;$('timeLeft').textContent=Math.max(0,left);if(left<=10){$('timerBadge').classList.add('danger');if(left>5)sfx('tick');else if(left>0)sfx('tickFast')}if(left<=0){clearInterval(roundTimer);sfx('timeout');setTimeout(()=>finish(false,'timeout'),330)}},1000)}
function finish(ok,reason=''){clearInterval(roundTimer);if(ok){stars+=10;correct++;sfx('ok')}else if(reason!=='timeout')sfx(reason==='skip'?'skip':'bad');sync();deal();show('game')}
function bind(){renderCategories();document.querySelectorAll('[data-mute]').forEach(b=>b.onclick=()=>{muted=!muted;muted?musicStop():musicStart();sync()});document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>{sfx('tap');show(b.dataset.menu)});document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>{sfx('tap');show('home')});$('back').onclick=()=>{sfx('tap');show('categories')};$('close').onclick=()=>{sfx('tap');show('game')};$('ok').onclick=()=>finish(true);$('skip').onclick=()=>finish(false,'skip');document.addEventListener('pointerdown',musicStart,{once:true});sync()}
bind();