// Semantic coverage layer for VIRA cards. Loaded after visuals.js.
(()=>{
const GENERIC=new Set(['paw-prints','bust-in-silhouette','fork-and-knife-with-plate','sports-medal','briefcase','teddy-bear','game-die','star','person-gesturing-ok']);
const X={
// animais
'alpaca':'llama','tamandua':'anteater','tatu':'armadillo','pelicano':'pelican','beija-flor':'hummingbird','pica-pau':'woodpecker','falcao':'eagle','salamandra':'lizard','cavalo-marinho':'seahorse','leao-marinho':'seal','enguia':'fish','peixe-palhaco':'tropical-fish','peixe-espada':'fish','ponei':'horse-face','bode':'goat','boi':'ox','bezerro':'cow-face','pintinho':'baby-chick','peru':'turkey','codorna':'bird','ganso':'goose','marreco':'duck','lebre':'rabbit-face','chinchila':'mouse-face','furao':'otter','guaxinim':'raccoon','gamba':'skunk','hiena':'wolf','leopardo':'leopard','onca':'leopard','pantera':'black-cat','guepardo':'leopard','puma':'cat-face','antilope':'deer','gazela':'deer','alce':'moose','rena':'deer','bisao':'bison','ornitorrinco':'duck','suricato':'mongoose','chimpanze':'monkey-face','orangotango':'orangutan','babuino':'monkey-face','lemure':'monkey-face','mico-leao-dourado':'monkey-face','carcara':'eagle','cacatua':'parrot','bem-te-vi':'bird','siri':'crab','ourico-do-mar':'shell','ourico':'hedgehog','centopeia':'bug','louva-a-deus':'bug','mariposa':'moth','cupim':'ant','cigarra':'cricket',
// comidas
'nhoque':'spaghetti','ravioli':'dumpling','risoto':'cooked-rice','feijoada':'pot-of-food','strogonoff':'pot-of-food','pure de batata':'potato','batata assada':'potato','batata chips':'potato','mandioca':'root-vegetable','polenta':'corn','farofa':'bowl-with-spoon','caldo':'pot-of-food','ovo cozido':'egg','salsicha':'hot-dog','presunto':'meat-on-bone','peixe assado':'fish','lula frita':'squid','moqueca':'pot-of-food','acaraje':'dumpling','escondidinho':'pot-of-food','empada':'pie','empadao':'pie','quibe':'croquette','esfiha':'stuffed-flatbread','pao frances':'baguette-bread','pao de forma':'bread','torrada':'bread','misto-quente':'sandwich','cheeseburger':'hamburger','x-salada':'hamburger','wrap':'burrito','nachos':'taco','guacamole':'avocado','cuscuz':'cooked-rice','aveia':'bowl-with-spoon','cappuccino':'hot-beverage','agua de coco':'coconut','vitamina':'cup-with-straw','milk-shake':'cup-with-straw','mousse':'custard','gelatina':'custard','brownie':'chocolate-bar','torta':'pie','cheesecake':'cake','pacoca':'peanuts','pe de moleque':'peanuts','cocada':'coconut','beijinho':'coconut','quindim':'custard','doce de leite':'custard','goiabada':'candy','romeu e julieta':'cheese-wedge','algodao-doce':'cotton-candy','castanha':'chestnut','nozes':'chestnut','pessego':'peach','mamao':'melon','tangerina':'tangerine','maracuja':'yellow-circle','goiaba':'green-apple','ameixa':'purple-circle','framboesa':'strawberry','amora':'blueberries','mirtilo':'blueberries','jabuticaba':'grapes','acerola':'cherries','caju':'cashew','pitaya':'dragon-fruit','beterraba':'root-vegetable','couve-flor':'broccoli','abobora':'pumpkin','palmito':'bamboo',
// personagens / profissoes
'imperador':'person-with-crown','imperatriz':'person-with-crown','mosqueteiro':'person-fencing','cacador':'bow-and-arrow','aventureiro':'person-hiking','capitao':'person-with-crown','general':'person-military','prisioneiro':'locked','bandido':'ninja','acrobata':'person-cartwheeling','malabarista':'juggling','domador':'circus-tent','roqueiro':'guitar','modelo':'person','celebridade':'glowing-star','poeta':'writing-hand','escultor':'artist-palette','jogador de futebol':'soccer-ball','lutador':'boxing-glove','piloto de corrida':'racing-car','motociclista':'motorcycle','alpinista':'person-climbing','patinador':'roller-skate','esquiador':'skis','mineiro':'pick','barista':'hot-beverage','mordomo':'person-tipping-hand','baba':'baby','presidente':'person-in-suit-levitating','guarda-costas':'guard','mochileiro':'backpack','naufrago':'desert-island','caipira':'farmer','treinador':'person-raising-hand','homem das cavernas':'person','mimico':'performing-arts','ilusionista':'magic-wand','bobo da corte':'clown-face','biomedico':'microscope','terapeuta ocupacional':'health-worker','quiropraxista':'person-massaging','cardiologista':'anatomical-heart','radiologista':'x-ray','anestesista':'syringe','auxiliar de enfermagem':'health-worker','tecnico de laboratorio':'test-tube','ortodontista':'tooth','zootecnista':'cow-face','pecuarista':'cow-face','operador de maquinas':'gear','motorista de onibus':'bus','capitao de navio':'ship','defensor publico':'balance-scale','escrivao':'writing-hand','oficial de justica':'judge','secretario':'memo','secretario executivo':'memo','corretor de imoveis':'house','corretor de seguros':'shield','publicitario':'megaphone','designer de interiores':'house','interprete':'speaking-head','sociologo':'people-holding-hands','antropologo':'busts-in-silhouette',
// esportes
'tenis de mesa':'ping-pong','marcha atletica':'person-walking','salto com vara':'person-jumping','lancamento de dardo':'bullseye','lancamento de disco':'flying-disc','corrida com barreiras':'person-running','revezamento':'person-running','hoquei sobre grama':'field-hockey','polo':'horse-racing','frescobol':'ping-pong','peteca':'badminton','queimada':'ball','bilhar':'pool-8-ball','damas':'black-square-button','patinacao artistica':'ice-skate','patinacao de velocidade':'ice-skate','hoquei de patins':'roller-skate','mountain bike':'mountain-bicyclist','ciclismo de pista':'person-biking','motovelocidade':'motorcycle','enduro':'motorcycle','slackline':'person-standing','skimboard':'person-surfing','stand up paddle':'person-surfing','bodyboard':'person-surfing','mergulho livre':'person-swimming','nado sincronizado':'person-swimming','saltos ornamentais':'person-swimming','canoagem slalom':'canoe','remo olimpico':'person-rowing-boat','pesca esportiva':'fishing-pole','tiro com arco':'bow-and-arrow','kickboxing':'boxing-glove','wrestling':'people-wrestling','sumo':'people-wrestling','capoeira':'person-cartwheeling','aikido':'martial-arts-uniform','kendo':'person-fencing','kung fu':'martial-arts-uniform','powerlifting':'person-lifting-weights','crossfit':'person-lifting-weights','ginastica ritmica':'person-cartwheeling','ginastica artistica':'person-cartwheeling','trampolim':'person-jumping','aerobica':'person-running','cheerleading':'pom-poms','danca esportiva':'person-dancing','patinacao inline':'roller-skate','escalada esportiva':'person-climbing','boulder':'person-climbing','montanhismo':'mountain','alpinismo':'person-climbing','orientacao':'compass','pentatlo moderno':'sports-medal','decatlo':'sports-medal','heptatlo':'sports-medal','biathlon':'skis','bobsled':'sled','luge':'sled','skeleton':'sled','esqui cross-country':'skis','salto de esqui':'skis','esqui alpino':'skis','snowboard cross':'snowboarder','wakeboard':'person-surfing','esqui aquatico':'person-surfing','parasailing':'parachute','ultimate frisbee':'flying-disc','goalball':'ball','netball':'basketball','corrida de saco':'person-jumping','futebol de botao':'soccer-ball','tenis de praia':'tennis',
// infantil
'balanco':'playground-slide','gangorra':'playground-slide','massinha':'artist-palette','xilofone':'musical-keyboard','cama elastica':'person-jumping','cubo magico':'game-die','jogo da memoria':'flower-playing-cards','domino':'game-die','lego':'bricks','prancha de surfe':'surfing'
};
const RULES={
'Ações':[
['washing',['lavar louca','lavar roupa','lavar cabelo']],['laundry',['estender roupa','passar roupa']],['bed',['arrumar cama']],['window',['limpar janela']],['broom',['varrer','passar pano','tirar poeira','aspirar']],['person-falling',['cair','tropecar','escorregar']],['baby',['engatinhar']],['person-walking',['marchar','subir escada','descer escada']],['person-cartwheeling',['girar','agachar','alongar','equilibrar','fazer malabarismo']],['basketball',['arremessar','rebater']],['shield',['defender']],['bottle-with-popping-cork',['abrir garrafa']],['canned-food',['abrir lata']],['hot-beverage',['tomar cafe']],['hair-pick',['secar cabelo','pentear cabelo']],['lipstick',['fazer maquiagem']],['razor',['fazer barba']],['shirt',['vestir camisa','tirar casaco']],['jeans',['vestir calca']],['running-shoe',['calcar sapato','amarrar cadarco']],['top-hat',['colocar chapeu']],['umbrella',['abrir guarda-chuva','fechar guarda-chuva']],['face-with-monocle',['espiar','procurar']],['hide',['esconder']],['horse-racing',['montar cavalo']],['glass-of-milk',['ordenhar vaca']],['dog-face',['dar comida ao cachorro']],['balloon',['soltar balao']],['doll',['brincar de boneca']],['racing-car',['brincar de carrinho']],['puzzle-piece',['montar quebra-cabeca']],['right-arrow',['empurrar']],['left-arrow',['puxar']],['straight-ruler',['medir']],['screwdriver',['parafusar']],['paintbrush',['pintar parede']]
],
'Comidas':[['pot-of-food',['feijoada','strogonoff','moqueca','caldo','sopa']],['pie',['empada','torta']],['potato',['batata']],['bread',['pao']],['hamburger',['burger','x-salada']],['cup-with-straw',['vitamina','milk-shake','refrigerante','suco']]],
'Profissões':[['health-worker',['medico','enferm','cirurg','pediatra','cardiologista','radiologista','anestesista']],['hammer-and-wrench',['tecnico','mecanico','engenheiro']],['writing-hand',['escritor','poeta','escrivao','roteirista']],['artist-palette',['designer','ilustrador','cartunista']],['microphone',['apresentador','locutor','radialista']],['briefcase',['gerente','diretor','empresario','administrador']],['farmer',['agric','fazendeiro','pecuarista']]],
'Personagens':[['person-fencing',['guerreiro','cavaleiro','gladiador','mosqueteiro','medieval']],['magic-wand',['magico','ilusionista','fada madrinha']],['person-hiking',['aventureiro','explorador','cacador de tesouros']],['performing-arts',['mimico','acrobata','malabarista']]],
'Esportes':[['person-running',['corrida','maratona','atletismo','revezamento']],['person-swimming',['natacao','mergulho','nado']],['person-biking',['ciclismo','bmx','bike']],['person-surfing',['surf','board','paddle']],['person-climbing',['escalada','alpinismo','boulder','montanhismo']],['boxing-glove',['boxe','kickboxing','muay','mma']],['martial-arts-uniform',['judo','karate','jiu-jitsu','taekwondo','aikido','kung fu']],['skis',['esqui','biathlon']],['roller-skate',['patinacao','patinete']]],
'Animais':[['bird',['ave','canario','bem-te-vi','codorna']],['fish',['peixe','enguia']],['cat-face',['felino','puma']],['dog-face',['canideo']],['bug',['inseto','centopeia','louva-a-deus']]],
'Infantil':[['toy',['brinquedo']],['balloon',['balao']],['bicycle',['bicicleta']],['rocket',['foguete']]]
};
function chooseRule(s,cat){for(const [icon,keys] of (RULES[cat]||[]))if(keys.some(k=>s.includes(k)))return icon;return null}
const oldIconFor=window.iconFor;
window.iconFor=function(word,cat){
 const s=norm(word);
 if(X[s])return X[s];
 const r=chooseRule(s,cat); if(r)return r;
 const old=oldIconFor(word,cat);
 if(old&&!GENERIC.has(old))return old;
 // category-specific non-abstract fallback: show a concrete visual related to the card class
 return {Animais:'dog-face',Personagens:'performing-arts',Comidas:'pot-of-food',Esportes:'person-running',Profissões:'person-technologist',Ações:'person-raising-hand',Infantil:'joystick',Tudo:'star'}[cat]||'star';
};
window.makeVisual=function(word,cat){return artCard(window.iconFor(word,cat))};
window.renderIcons=function(word,cat){return window.makeVisual(word,cat)};
})();