// VIRA illustration engine — semantic artwork from Microsoft's Fluent Emoji via Iconify (MIT)
const CAT=[['Animais','lion','c1'],['Personagens','superhero','c2'],['Comidas','pizza','c3'],['Esportes','soccer-ball','c4'],['Profissões','firefighter','c5'],['Ações','person-running','c6'],['Infantil','teddy-bear','c7'],['Tudo','game-die','all']];
const CDN='https://api.iconify.design/fluent-emoji/';
function norm(t){return String(t||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
const MAP={
Animais:[['lion',['leao']],['tiger-face',['tigre']],['elephant',['elefante']],['giraffe',['girafa']],['zebra',['zebra']],['monkey-face',['macaco']],['panda',['panda']],['bear',['urso']],['horse-face',['cavalo']],['cow-face',['vaca']],['pig-face',['porco']],['ewe',['ovelha']],['goat',['cabra']],['dog-face',['cachorro']],['cat-face',['gato']],['rabbit-face',['coelho']],['chicken',['galinha']],['rooster',['galo']],['duck',['pato']],['penguin',['pinguim']],['crocodile',['crocodilo']],['turtle',['tartaruga']],['frog',['sapo']],['shark',['tubarao']],['t-rex',['dinossauro']]],
Personagens:[['superhero',['super-heroi']],['princess',['princesa']],['prince',['principe']],['pirate-flag',['pirata']],['ninja',['ninja']],['mage',['mago']],['witch',['bruxa']],['fairy',['fada']],['astronaut',['astronauta']],['robot',['robo']],['person-fencing',['cavaleiro']],['king',['rei']],['queen',['rainha']],['clown-face',['palhaco']],['detective',['detetive']],['vampire',['vampiro']],['ghost',['fantasma']],['ogre',['monstro']],['merperson',['sereia']],['genie',['genio']],['cowboy-hat-face',['cowboy']],['person-fencing',['samurai']],['detective',['espiao']],['person-hiking',['explorador']],['cook',['chef maluco']]],
Comidas:[['pizza',['pizza']],['hamburger',['hamburguer']],['hot-dog',['cachorro-quente']],['french-fries',['batata frita']],['spaghetti',['macarrao']],['cooked-rice',['arroz']],['beans',['feijao']],['cut-of-meat',['churrasco']],['poultry-leg',['frango assado']],['cooking',['ovo frito']],['bread',['pao de queijo']],['stuffed-flatbread',['pastel']],['dumpling',['coxinha']],['flatbread',['tapioca']],['pancakes',['panqueca']],['birthday-cake',['bolo']],['chocolate-bar',['brigadeiro','chocolate']],['soft-ice-cream',['sorvete']],['popcorn',['pipoca']],['banana',['banana']],['red-apple',['maca']],['strawberry',['morango']],['watermelon',['melancia']],['grapes',['uva']],['tangerine',['laranja']],['pineapple',['abacaxi']],['ear-of-corn',['milho']],['cheese-wedge',['queijo']],['sushi',['sushi']]],
Esportes:[['soccer-ball',['futebol','futsal']],['basketball',['basquete']],['volleyball',['volei']],['tennis',['tenis']],['person-swimming',['natacao']],['person-running',['corrida']],['person-biking',['ciclismo']],['boxing-glove',['boxe']],['person-in-lotus-position',['judo']],['martial-arts-uniform',['karate']],['skateboard',['skate']],['person-surfing',['surfe']],['person-cartwheeling',['ginastica']],['handball',['handebol']],['ping-pong',['tenis de mesa']],['badminton',['badminton']],['baseball',['beisebol']],['rugby-football',['rugby']],['flag-in-hole',['golfe']],['bowling',['boliche']],['ice-skate',['patinacao']],['skis',['esqui']],['snowboarder',['snowboard']],['horse-racing',['hipismo']],['person-climbing',['escalada']],['canoe',['canoagem']],['person-rowing-boat',['remo']],['bow-and-arrow',['arco e flecha']],['person-jumping-rope',['pular corda']]],
Profissões:[['health-worker',['medico']],['health-worker',['enfermeiro']],['firefighter',['bombeiro']],['police-officer',['policial']],['teacher',['professor']],['cook',['cozinheiro']],['tooth',['dentista']],['dog-face',['veterinario']],['automobile',['motorista']],['pilot',['piloto']],['mechanic',['mecanico']],['electric-plug',['eletricista']],['construction-worker',['pedreiro']],['artist',['pintor']],['camera-with-flash',['fotografo']],['newspaper',['jornalista']],['singer',['cantor']],['performing-arts',['ator']],['person-dancing',['dancarino']],['person-getting-haircut',['cabeleireiro']],['barber-pole',['barbeiro']],['bread',['padeiro']],['person-tipping-hand',['garcom']],['shopping-bags',['vendedor']],['postbox',['carteiro']],['potted-plant',['jardineiro']],['farmer',['fazendeiro']],['technologist',['programador']],['triangular-ruler',['arquiteto']],['judge',['juiz']]],
Infantil:[['t-rex',['dinossauro']],['unicorn',['unicornio']],['teddy-bear',['ursinho']],['doll',['boneca']],['racing-car',['carrinho']],['locomotive',['trenzinho']],['airplane',['aviao de brinquedo']],['sailboat',['barquinho']],['soccer-ball',['bola']],['balloon',['balao']],['kite',['pipa']],['yo-yo',['ioio']],['person-cartwheeling',['bambole']],['kick-scooter',['patinete']],['bicycle',['bicicleta']],['playground-slide',['escorregador']],['person-cartwheeling',['balanco','gangorra']],['castle',['castelo']],['rocket',['foguete']],['star',['estrela']],['crescent-moon',['lua']],['sun',['sol']],['rainbow',['arco-iris']],['cloud',['nuvem']],['robot',['robo de brinquedo']],['building-construction',['blocos de montar']],['puzzle-piece',['quebra-cabeca']],['artist-palette',['massinha']],['books',['livro de historias']]]};
const FALLBACK={Animais:'lion',Personagens:'superhero',Comidas:'fork-and-knife-with-plate',Esportes:'sports-medal',Profissões:'briefcase',Ações:'person-running',Infantil:'teddy-bear',Tudo:'game-die'};
function iconFor(word,cat){let s=norm(word);if(cat==='Ações')return actionIcon(s);for(const [ico,terms] of MAP[cat]||[])if(terms.some(t=>s.includes(t)))return ico;return FALLBACK[cat]||'star'}
function actionIcon(s){const a=[['person-sleeping',['dorm','deitar']],['person-running',['correr','correndo']],['person-walking',['andar','caminh']],['person-dancing',['danc','girar']],['person-swimming',['nadar','mergul']],['person-climbing',['escal']],['person-biking',['pedalar']],['person-jumping-rope',['pular']],['person-gesturing-ok',['acenar','cumpriment']],['people-hugging',['abrac']],['person-eating',['comer']],['cup-with-straw',['beber']],['open-book',['ler']],['writing-hand',['escrever','desenhar']],['mobile-phone',['telefon']],['automobile',['dirigir']],['broom',['varrer','limpar']],['shower',['banho']],['toothbrush',['escovar']],['musical-notes',['cantar','assobiar']],['clapping-hands',['bater palma']],['face-with-hand-over-mouth',['rir']],['loudly-crying-face',['chorar']],['thinking-face',['pensar']],['face-screaming-in-fear',['assust']],['flexed-biceps',['forca','levantar']],['cooking',['cozinhar']],['wrapped-gift',['abrir presente']],['camera-with-flash',['fotograf']],['soccer-ball',['chutar']],['bullseye',['jogar']]];for(const [i,t] of a)if(t.some(x=>s.includes(x)))return i;return 'person-running'}
function modifier(word){let s=norm(word);if(s.includes('dormindo')||s.includes('cansado'))return 'zzz';if(s.includes('bravo'))return 'anger-symbol';if(s.includes('bebe'))return 'baby-symbol';if(s.includes('correndo'))return 'dash';if(s.includes('dancando'))return 'musical-notes';if(s.includes('assustado'))return 'face-screaming-in-fear';if(s.includes('voando'))return 'dizzy';if(s.includes('comendo'))return 'fork-and-knife';if(s.includes('comemorando')||s.includes('ganhando'))return 'party-popper';if(s.includes('caindo'))return 'dizzy';if(s.includes('treinando')||s.includes('trabalhando'))return 'flexed-biceps';if(s.includes('gigante'))return 'up-arrow';if(s.includes('quente'))return 'fire';if(s.includes('gelado'))return 'snowflake';if(s.includes('apimentado'))return 'hot-pepper';return ''}
function url(icon){return CDN+encodeURIComponent(icon)+'.svg'}
function img(icon,cls='mainIllo'){return `<img class="${cls}" src="${url(icon)}" alt="" loading="eager" decoding="async" onerror="this.onerror=null;this.src='${url('star')}'">`}
function artCard(main,badge=''){return `<div class="bankIllo">${img(main)}${badge?img(badge,'badgeIllo'):''}</div>`}
function makeVisual(word,cat){return artCard(iconFor(word,cat),modifier(word))}
function categoryVisual(cat){const x=CAT.find(v=>v[0]===cat);return artCard(x?x[1]:FALLBACK[cat]||'star')}
function renderIcons(word,cat){return makeVisual(word,cat)}